### ISSUE TITLE
Any number for performance benchmark?

### ISSUE THREAD

**Issue by cih-y2k** [Morgan-Stanley/SilverKing#2]
The project looks promising, is there any number about its performance?

**Comment by gjms** [comment]
At a high level, performance is “fast”. Exact numbers depend on what test is being run, and the environment in which it is being run. We don’t yet have publically reproducible numbers, but here are a few anecdotal observations. (These observations hold for weaker/untuned hardware, but with software options tuned for higher performance [e.g. RAM storage, loose consistency]. Using better hardware/tuning will result in better performance. Changing software options will lower performance.)

Single operation latency: ~150 us. 

Scale: At least tens of thousands of concurrent writers and readers, and thousands of servers.

Throughput: For small values, a single client thread can write/read around 100,000 key-value pairs per second using bulk operations. Adding threads increases throughput. With larger values, throughput becomes constrained by the network (we have tested through 10G).
